name: test

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: ['8.2', '8.3', '8.4', '8.5']

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: error_reporting=E_ALL
          tools: composer:v2

      - name: Install dependencies
        run: composer install

      - name: Execute PHPCS
        run: |
          ./vendor/bin/phpcs --standard=PSR12 src/ tests/
        if: ${{ matrix.php == '8.5' }}

      - name: Execute PHPStan
        run: |
          ./vendor/bin/phpstan analyse
        if: ${{ matrix.php == '8.5' }}

      - name: Execute tests
        run: ./vendor/bin/phpunit
