name: test

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: ['5.3.3', '5.3', '5.4', '5.5', '5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0', '8.1', '8.2', '8.3', '8.4']

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          ini-values: error_reporting=E_ALL
          tools: composer:v2

      - name: Install dependencies
        run: composer install

      - name: Execute PHPCS
        run: |
          composer require "squizlabs/php_codesniffer=3.13.2"
          ./vendor/bin/phpcs --standard=PSR12 src/ tests/
        if: ${{ matrix.php == '8.4' }}

      - name: Execute PHPStan
        run: |
          composer require phpstan/phpstan:2.1.17 phpstan/phpstan-phpunit:2.0.6
          ./vendor/bin/phpstan analyse
        if: ${{ matrix.php == '8.4' }}

      - name: Execute tests
        run: ./vendor/bin/phpunit
